### ISSUE TITLE
Tips to Improve your project

### ISSUE THREAD

**Issue by Akramz** [Ibtissam1996/Zabbix-Project#1]
Working on these tasks will improve the quality of your project and result in a better evaluation for you:
- Change the name of your project to reflect the meaning of it. 
- Git manages source files, extract your zip into a traceable project structure.
- I did not find any web service/API/site.
- I could not read the `RTF` files, convert them to `Bash` files, and make sure they're executable.

**Comment by Ibtissam1996** [comment]
if I try to extract my zip into a traceable project structure he give this
error

Le lun. 8 juin 2020 à 18:58, Akram Zaytar <notifications@github.com> a
écrit :

**Comment by Ibtissam1996** [comment]
I think I solved the problem
Thank you sir.

Le lun. 15 juin 2020 à 15:36, Akram Zaytar <notifications@github.com> a
écrit :
